"""Domain models for the Journey content store."""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class StreamingLinks(BaseModel):
    spotify: Optional[str] = None
    apple_music: Optional[str] = None
    youtube: Optional[str] = None


class Song(BaseModel):
    position: int
    title: str
    artist: str
    month_year: str  # string, e.g. "November 1936" or "1954"
    place: str       # where recorded (MusicBrainz-sourced in pipeline)
    blurb: str
    blurb_audio_url: Optional[str] = None  # TTS narration, pre-generated by pipeline
    preview_url: Optional[str] = None
    image_url: Optional[str] = None
    streaming_links: StreamingLinks = Field(default_factory=StreamingLinks)


class Journey(BaseModel):
    id: str  # slug, e.g. "journey:great-migration"
    title: str
    subtitle: str = ""
    theme: str
    blurb: str
    closing_paragraph: str = ""
    intro_audio_url: Optional[str] = None   # TTS narration of blurb
    outro_audio_url: Optional[str] = None   # TTS narration of closing_paragraph
    image_url: Optional[str] = None
    prompt_chips: list[str] = Field(default_factory=list)
    categories: list[str] = Field(default_factory=list)
    songs: list[Song] = Field(default_factory=list)
